name: "Build"
on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build-firefox
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: "."
          filename: "{name}-{version}.xpi"
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock",".github" ]'

      - name: "web-ext build"
        id: web-ext-build-chrome
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: "."
          filename: "{name}-{version}.zip"
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock",".github" ]'

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "Firefox xpi"
          path: ${{ steps.web-ext-build-firefox.outputs.target }}
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "Chrome zip"
          path: ${{ steps.web-ext-build-chrome.outputs.target }}